#CREATE DATABASE ea WITH OWNER = postgres ENCODING = 'UTF8' TABLESPACE = pg_default CONNECTION LIMIT = -1;

CREATE ROLE gr_ea_editors_ldap SUPERUSER NOINHERIT NOREPLICATION;

#GRANT CONNECT ON DATABASE ea TO gr_ea_editors_ldap;
#GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO gr_ea_editors_ldap;
#GRANT SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO gr_ea_editors_ldap;

CREATE ROLE gr_ea_viewers_ldap NOINHERIT NOREPLICATION;

#GRANT CONNECT ON DATABASE ea TO gr_ea_viewers_ldap;
#GRANT SELECT ON ALL TABLES IN SCHEMA public TO gr_ea_viewers_ldap;
#GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO gr_ea_viewers_ldap;

REVOKE CONNECT, TEMPORARY ON DATABASE ea FROM public;
